LambdaLabs/lambda-docs

config.toml, layouts/partials/navbar.html
=> Hide site title in top navbar

static/google84b5f2e9b6481780.html
See: https://support.google.com/webmasters/answer/9008080#html_verification
=> Verify site ownership for Google Search Console

content/en/cloud/guides/iptables-flush-rules.md
=> Add guide: "Use iptables to disable firewall"

content/en/cloud/faq/grayed-out-instance-types.md
=> Add FAQ: "Why are some instance types grayed out when I try to launch an instance?"

content/en/cloud/_index.md, content/en/cloud/faq/_index.md, content/en/cloud/faq/more-than-one-ssh-key.md
=> Add FAQ: "Is it possible to use more than one SSH key?"

content/en/linux/faq/_index.md, content/en/linux/faq/recovery-images.md
~~- [ ] Symlinks to `/current/lambda-recovery-(bionic|focal|jammy).iso`~~ → #72
Closes: #51
=> Add FAQ: "Where can I download recovery images?"

content/en/cloud/faq/cannot-find-nvidia-cudnn.md
=> Add FAQ: "Why can't my program find the NVIDIA cuDNN library?"

content/en/cloud/estimate-job-cost.md
=> Add FAQ: "Can you provide an estimate of how much a job will cost?"

Dockerfile, README.md, docker-compose.yaml
=> Improve README

content/en/_index.md
Closes: #130
NB: I'm arbitrarily limiting the number of FAQs per product to 6.
=> Update list of top FAQs

content/en/servers/user-guides.md
=> Add FAQ: "Where can I download the user manual for my server chassis?"

content/en/cloud/learn-private-ip-address.md
=> Add FAQ: "How do I learn my instance's private IP address and other info?"

content/en/cloud/network-bandwidth.md
=> Update "What network bandwidth does Lambda GPU Cloud provide?"

content/en/cloud/api-features.md, content/en/cloud/terminate-instance-api.md
=> Add FAQ: "What can I do with the Cloud API?"

content/en/cloud/how-do-i-change-my-password.md, content/en/cloud/how-long-instance-launch.md, content/en/cloud/on-demand-instance-invoicing.md
=> Add FAQ: "How long does it take for instances to launch?"

content/en/cloud/api-add-ssh-key.md
=> Document how to use API to list and delete SSH keys

content/en/cloud/api-features.md, content/en/cloud/list-details-specific-instance.md, content/en/cloud/list-file-systems-api.md
=> Add FAQ: "How do I list my file systems using the Cloud API?"

content/en/cloud/on-demand-instance-invoicing.md
=> Update "How are on-demand instances invoiced?" FAQ for weekly billing

content/en/linux/remove-reinstall-lambda-stack.md
TY @chuanli11 for bringing this to my attention.
=> Update versions in "How do I remove and reinstall Lambda Stack?"

content/en/cloud/faq/support-kubernetes.md
=> Add FAQ: "Do you support Kubernetes (K8s)?"

config.toml
=> Remove link to knowledge base

content/en/cloud/more-than-one-ssh-key.md, content/en/cloud/ssh-key-from-github.md
=> Add FAQ: "How do I import an SSH key from a GitHub account?"

content/en/cloud/network-bandwidth.md
=> Improve disclaimer WRT Cloud network bandwidth

.devcontainer/devcontainer.json
=> Add dev container config

content/en/cloud/use-persistent-storage.md
=> Add note WRT max number of file systems

content/en/cloud/block-object-storage.md
Added FAQ for block and object storage
Closes: #233
=> FAQ: block and object storage

content/en/cloud/ssh-key-formats.md
=> Add FAQ: "What SSH key formats are supported?"

content/en/cloud/persistent-storage-capacity.md
=> Add FAQ: "What is the capacity of persistent storage file systems?"

content/en/cloud/limit-file-system-usage.md
=> Add FAQ: "Can I set a limit (quota) on my file system usage?"

content/en/cloud/remote-mount-persistent-storage.md
Re: Issue #231 
Added FAQ: "Can I remotely mount persistent storage?"
=> added remote mount FAQ

content/en/cloud/limit-file-system-usage.md
=> Add tip WRT using API to learn file system usage

config.toml
=> Update feedback buttons to link to Support contact form

content/en/linux/rsync-to-copy-and-synchronize.md
=> Add FAQ: "How do I use rsync to copy and synchronize files?"

content/en/cloud/change-billing-address.md, content/en/cloud/cloud-dashboard/index.md, content/en/cloud/problem-processing-payment-method.md
=> Add FAQ: "How do I change my billing address?"

content/en/linux/recovery-images.md, content/en/linux/reinstall-servers.md
=> Add FAQ: "How do I reinstall Ubuntu and Lambda Stack on my server?"
